apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ut9q0x1t7-dotnet-basic
  janus-idp.io/tekton: ut9q0x1t7-dotnet-basic
  backstage.io/kubernetes-id: ut9q0x1t7-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ut9q0x1t7-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
